### PR TITLE
Support parsing json in MySql binglog

### PR DESCRIPTION
**Pull request by caicancai**
There is an API in mysql-connector-java that supports parsing the json in MySql binlog, so you can call it directly
屏幕截图 2023-04-14 155947

### CODE REVIEW

**Comment by Xuxiaotuan** [comment]
and （ time、char ） field type

**Comment by caicancai** [comment]
@barryoneill hello, Is it convenient to merge it?

**Comment by barryoneill** [comment]
Hello @caicancai - I'd prefer to have a little test coverage in place first, so I just raised https://github.com/laserdisc-io/mysql-binlog-stream/pull/392, then I'll merge this and update the test.

**Comment by barryoneill** [comment]
appears to have broken with the latest from master.  I'll pull it in anyway, and fix it up

**Comment by caicancai** [comment]
thank you

**Comment by barryoneill** [comment]
[v3.0.0-RC1](https://github.com/laserdisc-io/mysql-binlog-stream/releases/tag/v3.0.0-RC1) has just been published, and will available in maven central in a few hours.

**Pull request merged**
